<?php
use Kernel\Security\Vulnerability\Xss;
use Kernel\Security\Vulnerability\Csrf;
use Kernel\Html\Attribute;
use Kernel\Html\Builder;
use Kernel\Html\Output;
use Kernel\Convert\Encoded;
use Kernel\Convert\Number;
use Kernel\Url\Location;
?>



<!-- 
Vue du composant Exemple.
Author: chris
Version: 1.0
Categorie: Component template
 -->
<exemple>
	<p>Le composant Exemple fonctionne !</p>
</exemple>