<?php
use Kernel\Security\Vulnerability\Xss;
use Kernel\Security\Vulnerability\Csrf;
use Kernel\Html\Attribute;
use Kernel\Html\Builder;
use Kernel\Html\Output;
use Kernel\Convert\Encoded;
use Kernel\Convert\Number;
use Kernel\Url\Location;
?>



<!-- 
Vue du composant Accueil.
Author: chris
Version: 1.0
Categorie: Component template
 -->
<accueil>
    <section>
        <div>
            <h1>TypeScript c'est JavaScript avec une syntaxe pour les types.</h1>
            <p>
                TypeScript est un langage de programmation libre développé et maintenu par Microsoft. Il est un sur-ensemble de JavaScript, et ajoute des fonctionnalités comme les types statiques et les classes.
            </p>
        </div>
        <div>
            <pre class="boxcode"><code class="language-TS">
interface User {
  name: string;
  id: number;
}
                </code></pre>
        </div>

    </section>
    <section class="versionSection">
        <p>La version actuelle de TypeScript est de <a class="version" href=""> 4.8</a> et la prochaine est la <a class="version" href="">4.9</a></p>
    </section>
</accueil>