<?php

use Kernel\Io\Convert\Image;
use Kernel\Security\Vulnerability\Xss;
use Kernel\Security\Vulnerability\Csrf;
use Kernel\Html\Attribute;
use Kernel\Html\Builder;
use Kernel\Html\Output;
use Kernel\Convert\Encoded;
use Kernel\Convert\Number;
use Kernel\Url\Location;
?>



<!-- 
Vue du composant Navbar.
Author: chris
Version: 1.0
Categorie: Component template
 -->
<navbar>
	<ul>
        <li>
            <a href="accueil">
                <?= Image::svg("tsLogo") ?>
                <span>TypeScript IUT</span>
            </a>
        </li>
        <li>
            <a href="documentation">
                Documentation
            </a>
        </li>
        <li>
            <a href="manuel">
                Manuel
            </a>
        </li>
    </ul>
</navbar>